spring:
  profiles:
    active: local
    group:
      "local": "local, common"
      "development": "development,common"
  h2:
    console:
      enabled: true
  cache:
    ehcache:
      config: "classpath:ehcache.xml"
  #spring:
  #  profiles:
  #    group:
  #      "local": "local, common"
  #      "development": "development,common"
  #    active: development

#  redis:
#    port: 6379
#    host: 127.0.0.1

  servlet:
    multipart:
      maxFileSize: 10MB #최대 파일 사이즈
      maxRequestSize: 30MB #최대 요청 사이즈
      # 즉 한파일에 10MB 이하 총 30MB이하의 이미지를 올려야 한다는 의미

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: foo
      # auto-offset-reset: earliest
      # key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      # key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: jdbc:h2:mem:db;MODE=MYSQL;
    #    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  jpa:
    #    추가해준 부분
    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    properties:
      hibernate:
        #        show_sql: true  # Hibernate가 DB에 수행하는 모든 쿼리문을 콘솔에 출력함. 겹치기 때문에 굳이 안넣어도 될듯
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    hibernate:
      ddl-auto: create

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace




#Secretkey
jwt:
  token:
    access-token-secret: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA
    refresh-token-secret: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpAB
  admin : AAABnvxRVklrnYxKZ0aHgTBcXukeZygoC
  secret: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA


#aws



---
# 공통
spring:
  config:
    activate:
      on-profile: "common"
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB


logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR

#          spring.h2.console.enabled=true
#          spring.datasource.url=jdbc:h2:mem:db;MODE=MYSQL;
#          spring.datasource.username=sa
#          spring.datasource.password=
#          spring.thymeleaf.cache=false